resolver: lts-10.4
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
# - location:
#    git: https://github.com/commercialhaskell/stack.git
#    commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
# - location: https://github.com/commercialhaskell/stack/commit/e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#   extra-dep: true
#  subdirs:
#  - auto-update
#  - wai
packages:
  - .
  - location:
      git: https://github.com/statusfailed/machines-attoparsec.git
      commit: 2067202a97c478fc5b09bd61fc3194d83dfe4340
    extra-dep: true
